/* USER_SIGNUP */
export const USER_SIGNUP_STARTED = 'USER_SIGNUP_STARTED';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE';

/* USER_LOGIN */
export const USER_LOGIN_STARTED = 'USER_LOGIN_STARTED';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
/* USER_TOKEN ACCESS */

export const USER_ACCESS_TOKEN_STARTED = 'USER_ACCESS_TOKEN_STARTED';
export const USER_ACCESS_TOKEN_SUCCESS = 'USER_ACCESS_TOKEN_SUCCESS';
export const USER_ACCESS_TOKEN_FAILURE = 'USER_ACCESS_TOKEN_FAILURE';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_PRELOGIN = 'USER_PRELOGIN';

/* USER_TOKEN REFRESH */
export const USER_REFRESH_TOKEN_STARTED = 'USER_REFRESH_TOKEN_STARTED';
export const USER_REFRESH_TOKEN_SUCCESS = 'USER_REFRESH_TOKEN_SUCCESS';
export const USER_REFRESH_TOKEN_FAILURE = 'USER_REFRESH_TOKEN_FAILURE';
export const USER_REFRESH_TOKEN_INT = 'USER_REFRESH_TOKEN_INT';

/*  ADD_TRACK_PLAYING */
export const ADD_TRACK_PLAYING = 'ADD_TRACK_PLAYING';

/*  TRACK FILTERS */
export const ADD_TRACK_FILTER = 'ADD_TRACK_FILTER';
export const ADD_TRACK_FILTER_YEAR = 'ADD_TRACK_FILTER_YEAR';
